### PR TITLE
Fix bugs caused by layer id conflict

### LINKED ISSUE #441: Broken icon should be displayed with layer errors only from the parent map
The `layerError.js` util is listening for errors globally when it should be listening only to the errors on the map the layer menu is contained in. This can be reproduced with the multipleMaps.html file in the example folder. The screenshot below shows the icon displayed on the second map after detecting the error from the first map.

image

### LINKED ISSUE #442: Issues with layer groups in multiple maps
When there are multiple maps in a page using the layer menu the layers within the group are displayed only on one layer menu and are missing from the rest. The toggle also seems to be interconnected. For example, when I click the arrow on the layer group in the second map the group in the first map expands or collapses. The screenshot shows the difference in the Justicemap group.
image

### PR DESCRIPTION
**Pull request by crisner**
Fixes #442 (<=== Add issue number here) &&
Fixes #441

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by crisner** [comment]
The bugs when using multiple maps in a single page was because there was more than one id with the same name. Refactored all id names to include the id of the map container. This solved the issue #442 and #441. 

Screenshot after the fix:
oimBug

**Comment by crisner** [comment]
I caught another weird bug where the OIM layers from one map were interfering with the OIM layers in the other map and removed the error icons from other layers in the first map when one of the OIM layers were clicked. This has also been fixed.

File: src/AllLayers.js [hunk 1]
```diff
@@ -61,6 +37,31 @@ L.LayerGroup.environmentalLayers = L.LayerGroup.extend(
 
       this.options.layers = param;
 
+      this._OpenInfraMap_Power = L.tileLayer('https://tiles-{s}.openinframap.org/power/{z}/{x}/{y}.png', {
```
Comment (crisner) [inline src/AllLayers.js]: I am a bit worried about moving these layers here but this seems to fix the issue of cross-wiring between layers when we have multiple maps on the page as mentioned here https://github.com/publiclab/leaflet-environmental-layers/pull/443#issuecomment-595771022

It's hard to test how these layers behave when added to the map because they don't work anymore. We could also comment them out till it is fixed.

**Comment by crisner** [comment]
There are a couple of failing tests. I'll look into them fixed later tonight or tomorrow.

**Comment by crisner** [comment]
image
image
example_multipleMaps html(Galaxy S5)

**Comment by crisner** [comment]
@jywarren, @sagarpreet-chadha, this PR fixes bugs from recent changes, fixes tests that were causing errors in the master branch and is ready for review and merge. Thanks!

File: src/AllLayers.js (hunk 1 above)
Comment (jywarren) [reply src/AllLayers.js]: Ah ok -- and noting #387 as the bug to fix for that. Thanks!

**Comment by jywarren** [comment]
Great work!!

**Comment by jywarren** [comment]
Thank you!!!
